image: 
  name: python:3.8-buster

cache:
  paths:
    - .venv

variables:
  poetry: .venv/bin/poetry

stages:
  - lint
  - build
  - test
  - version
  - deliver

setup:
  stage: .pre
  script:
    - python -m venv .venv
    - .venv/bin/pip -q install poetry
    - .venv/bin/poetry config virtualenvs.in-project true
    - .venv/bin/poetry install

test:
  stage: test
  script:
    - ${poetry} run python -m unittest tests/*.py

deliver:
  stage: deliver
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
  script:
    - ${poetry} publish --build --username "__token__" --password ${PYPY_TOKEN}

