#!/usr/bin/env python3

import argparse, sys, re

def get_parser():
    desc = 'Reads stdin for git log output and extract branch name from last merge'
    parser = argparse.ArgumentParser(description=desc)
    return parser

def main():
    parser = get_parser()
    args = parser.parse_args()
    log = sys.stdin.read()
    match = re.search(r"Merge branch \'(.*)\' into \'.*\'", log)
    print(match.group(1))

if __name__ == '__main__':
    main()
