#!/bin/bash
SCRIPT_DIR="$(pwd)/_devops/ci/version"
export PATH="${SCRIPT_DIR}:${PATH}"

last_version=$(last-release)
merge_branch=$(git log | merge-branch)
new_version=$(version-bump ${last_version} $merge_branch)
echo "Bump for branch: $merge_branch"
echo "New version: $new_version"
git tag -a "v${new_version}" -m "Auto versioning for version $new_version"
